// Sample Users Data
export const users = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "admin",
    active: true,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    role: "user",
    active: true,
  },
  {
    id: 3,
    name: "Carol Lee",
    email: "carol.lee@example.com",
    role: "user",
    active: false,
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@example.com",
    role: "moderator",
    active: true,
  },
  {
    id: 5,
    name: "Eva Green",
    email: "eva.green@example.com",
    role: "user",
    active: true,
  },
];

// Sample Products Data
export const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    brand: "Logitech",
    category: "Mouse",
    price: 29.99,
    inStock: true,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    brand: "Keychron",
    category: "Keyboard",
    price: 89.99,
    inStock: true,
  },
  {
    id: 3,
    name: "USB-C Hub",
    brand: "Anker",
    category: "Hub",
    price: 39.99,
    inStock: false,
  },
  {
    id: 4,
    name: "Webcam 1080p",
    brand: "Logitech",
    category: "Webcam",
    price: 49.99,
    inStock: true,
  },
  {
    id: 5,
    name: "External SSD 1TB",
    brand: "Samsung",
    category: "Storage",
    price: 119.99,
    inStock: true,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    brand: "JBL",
    category: "Speaker",
    price: 59.99,
    inStock: false,
  },
  {
    id: 7,
    name: "Gaming Headset",
    brand: "Razer",
    category: "Headset",
    price: 79.99,
    inStock: true,
  },
  {
    id: 8,
    name: "Portable Monitor",
    brand: "ASUS",
    category: "Monitor",
    price: 189.99,
    inStock: true,
  },
  {
    id: 9,
    name: "Wireless Charger",
    brand: "Belkin",
    category: "Charger",
    price: 24.99,
    inStock: true,
  },
  {
    id: 10,
    name: "Ergonomic Mouse Pad",
    brand: "3M",
    category: "Mouse Pad",
    price: 14.99,
    inStock: true,
  },
  {
    id: 11,
    name: "Docking Station",
    brand: "Dell",
    category: "Dock",
    price: 129.99,
    inStock: false,
  },
  {
    id: 12,
    name: "Smart LED Desk Lamp",
    brand: "BenQ",
    category: "Lighting",
    price: 69.99,
    inStock: true,
  },
  {
    id: 13,
    name: "Noise Cancelling Earbuds",
    brand: "Sony",
    category: "Earbuds",
    price: 149.99,
    inStock: true,
  },
  {
    id: 14,
    name: "USB Microphone",
    brand: "Blue",
    category: "Microphone",
    price: 99.99,
    inStock: false,
  },
  {
    id: 15,
    name: "Graphic Drawing Tablet",
    brand: "Wacom",
    category: "Tablet",
    price: 249.99,
    inStock: true,
  },
  {
    id: 16,
    name: "Wi-Fi 6 Router",
    brand: "TP-Link",
    category: "Router",
    price: 159.99,
    inStock: true,
  },
];
